### ISSUE TITLE
P54 Test is not failing for me

### ISSUE THREAD

**Issue by Foxandxss** [teropa/build-your-own-angularjs#292]
The test in here is not failing for me out of the box.

**Comment by teropa** [comment]
Is that the first test case for `$watchGroup` (`"takes watches as an array and calls listener with arrays"`). It should fail as `$watchGroup` doesn't exist at the time when the test is added?

**Comment by Foxandxss** [comment]
No, it is the `allows destroying several $watches during digest` but I don't remember why it was failing. Damn be for not being more concrete on the issues.

I am busy atm and I guess you're planning a release, but if you want to, you could clone my own copy of this project, go to page 49 (where `destroying a watch` starts) and implement from there:

https://github.com/Foxandxss/my_angular/commit/6ed1221480a07aaff52564c90b09c21bbbe936af

You could get that commit and continue from there if you want to.

**Comment by teropa** [comment]
Right. The `allows destroying several $watches during digest` test is set up so that it only _starts_ failing when previous test if fixed by moving from `push` and `forEach` to `unshift` and `forEachRight`. Since in that commit all the tests are already there, the last one does indeed not fail at first. Thanks!

**Comment by caolinjian** [comment]
@teropa  angular define 'length = watchers.length' and use ' while (length--) ' to loop.
We use forEach or forEachRight .I think the case "if (watcher) {" isn't needed. 
~ o(_￣▽￣_)ブ
